# version: '3'
# services:
#   web:
#     build: .
#     ports:
#       - "3000:3000"

version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ISA
      MYSQL_USER: sa
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: